import type {Metadata} from 'next'
import {ReactNode} from "react";
import {Domine, Josefin_Sans,} from 'next/font/google'
import './globals.css'
import Navigation from "@/components/navigation";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const domine = Domine({subsets: ['latin'], weight: "400", variable: "--font-domine"})
const josefineSans = Josefin_Sans({subsets: ['latin'], weight: ["300", "400"], variable: "--font-josefine-sans"})


export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">

        <body
            className={`${domine.variable} ${josefineSans.variable}`}>
        <Navigation/>
        {children}</body>
        </html>
    )
}
